
version: '3.8'

services:

  db:
    restart: "on-failure"

  rabbit:
    ports:
      - "9998:15672"

  back:
    restart: "on-failure"

    environment:
      BUILD_TYPE: "PROD" 

  front:
    build: 
      dockerfile: Dockerfile-prod
    # restart: "on-failure"

#     environment:
#       BUILD_TYPE: "Production" 

  nginx:
    build: 
      context: .
      dockerfile: ./_build/nginx/Dockerfile-prod

    restart: "on-failure"

    ports:
      - "8081:80"

