version: '3.8'

services:

  db:
    restart: "no"

    ports:
      - "5432:5432"


  adminer:
    restart: "no"

    # environment:
    #   ADMINER_DEFAULT_SYSTEM: pgsql
    #   ADMINER_DEFAULT_SERVER: postgres
    #   ADMINER_DEFAULT_DATABASE: ${DATABASE_DB}

    networks:
      - back


  back:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    environment:
      ENV: 'DEV'

    # volumes:
    #   - ./api:/app


  front:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t

    # ports:
    #   - "3000:3000"

    # volumes:
    #   - ./site:/app


  nginx:
    restart: "no"

    stdin_open:  true # docker run -i
    tty: true        # docker run -t


