name: Build and Deploy

on:
  push:
    branches:
      - '*'

  create:
    tags:
      - '*'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: cd site

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build


  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: ssh-action/ssh-action@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd /var/www/ftlwatch3dev
            git pull
            make
            make migrate


  # deploy-dev:
  #   name: Deploy to Development
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags/')

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Deploy to Development
  #       run: |
  #         # Add your development deployment script/command here
  #         # For example, you can use SCP, rsync, or other deployment methods
  #         # Make sure to replace the placeholders with actual values

